### ISSUE TITLE
Improve detection

### ISSUE THREAD

**Issue by mtschirs** [swozniak/googlifier#1]
Hi swozniak, just found your project when looking for applications of js-objectdetect. You can reduce false positives by first detecting a face and then detecting eyes within a region of interest on that face. This is the "recommended" way for eye detection and increases detection as well as runtime performance, since the face classifier is much more lightweight than its eye counterpart.

**Comment by swozniak** [comment]
Hey @mtschirs,
Thanks for the suggestion (and your library!). That sounds notably more efficient. Can I pass in the canvas regions from the face detection to a new detector with the eye qualifier?

**Comment by mtschirs** [comment]
See pull request #2 (https://github.com/mtschirs/googlifier)

**Comment by swozniak** [comment]
Checked out your latest. It's much more effective and efficient.
I appreciate the extra code abstraction and enhancements as well. Very clean contribution.

Thanks so much!

**Comment by mtschirs** [comment]
It was fun playing around with that addon in Chrome. Also, it seems to have gotten some media attention recently! Still, if you want to put more time into this, there are two possible areas of improvement I can think of right now:
- Some websites change the image src twice, but googlifier only googlifies on first change (so these images remain 'ungooglified')
- Background images are not googlified
